### ISSUE TITLE
Обновил оформление

### ISSUE THREAD

**Issue by zerobig** [egorshishkovets/app112#3]
В плане оформления я бы попробовал вот такой ход. Установил бы обычный bootstrap, а потом уже начал бы от этого "плясать". Это конечно на любителя и я не навязываю. Но по сравнению с тем, что выдал ты, смотрится наверное приятнее.

Посмотри у меня ветку [new-css](https://github.com/zerobig/app112/tree/new-css). Я пока не стал объединять её с основным репозиторием.

Переработал две формы: equipment#index и equipment#_form. Кода форм стало резко меньше и формы стали более читабельные. Конечно не только из-за bootstrap, но из счет ещё одного gem'а - bootstrap_form

**Comment by egorshishkovets** [comment]
Посмотрел оформление, действительно проучилось лучше, буду дорабатывать эту
версию, пока изучаю новые гемы

воскресенье, 30 октября 2016 г. пользователь zerobig написал:

**Comment by zerobig** [comment]
Тогда объединяю с основной веткой и делаю pull request.

**Comment by zerobig** [comment]
Надо же! Предыдущий pull request сам обновился после объединения. Интересно.

**Comment by egorshishkovets** [comment]
Хорошо, ещё посмотрел про согласование, получится ли настроить роли? Нужно
же получается предоставить доступ к этому полю роли согласующий

вторник, 1 ноября 2016 г. пользователь zerobig написал:

**Comment by zerobig** [comment]
Да. Конечно получится. Я пока особо с этим не заморачивался, но можешь посмотреть пример app/views/equipment/index.html.erb, 46:
```
<% if (equipment.is_approval) && (can? :manage, equipment) %>
```
Заведём право :approve. Заменим :manage на это новое право. И добавим проверку прав в контроллере, чтобы кто-нибудь ловкий не смог обойти используя обращение к контроллерам напрямую. А насчет доступа к полю БД, на мой взгляд, беспокоиться не надо. Это отсекается на слое контроллера.
Как-то так.
